apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-auth0-test-service
  labels:
    app: auth0-test-app 
spec:
  selector:
    app: auth0-test-app 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
