apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-auth0-test-service
  namespace: non-prod-1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  labels:
    app: auth0-test-app 
spec:
  selector:
    app: auth0-test-app 

  ports:
    - port: 80
      targetPort: 8080

  type: LoadBalancer
