spring:
  application:
    name: test-project
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/test_db"
    username: local
    password: local
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    user:
      name: rohit
      password: admin
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/
server:
  port: 8090

auth0:
  audience: https://menu-api.example.com
  domain: dev-sv8styw0.us.auth0.com